theme: just-the-docs
url: https://platform.devantler.tech
title: "ðŸš€â›´ï¸ Devantler Tech Platform"
description: >-
  A hybrid kubernetes platform for Devantler Tech, built with Hetzner, Cloudflare, Omni and Talos.

plugins:
  - jekyll-gfm-admonitions

aux_links:
  "<img src=\"https:\/\/raw.githubusercontent.com\/devantler-tech\/ksail\/refs\/heads\/main\/docs\/images\/github-mark-white.png\" alt=\"GitHub\" width=\"18\" height=\"18\">&nbsp;&nbsp;devantler-tech/platform":
    - "//github.com/devantler-tech/platform"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

gh_edit_link: true
gh_edit_link_text: Edit this page on GitHub.
gh_edit_repository: https://github.com/devantler-tech/platform
gh_edit_branch: main
gh_edit_view_mode: tree

back_to_top: true
back_to_top_text: "Back to top"

footer_content: 'Built by <a href="https://github.com/devantler">devantler</a><br>Distributed under the <a href="https://opensource.org/licenses/Apache-2.0">Apache license.</a>'

exclude:
  - .github/
  - .vscode/
  - hetzner/
  - k8s/
  - k8s-old/
  - talos/
  - .gitignore
  - .policyignore
  - .releaserc
  - .sops.yaml
  - kind.yaml
  - ksail.yaml
