---
apiVersion: v1
kind: ConfigMap
metadata:
  name: variables-cluster
  namespace: flux-system
data:
  cloudflared_tunnel_id: 18508e52-a9d7-466c-b85e-1fa102b3542e
  domain: platform.devantler.tech
  github_app_client_id: Iv23limfvbk93bAXZI6b
  issuer_group: cert-manager.k8s.cloudflare.com
  issuer_kind: ClusterOriginIssuer
  issuer_name: cloudflare-origin
  nextcloud_db_storage_size: 30Gi
  traefik_service_type: ClusterIP
