---
apiVersion: v1
kind: ConfigMap
metadata:
  name: variables-cluster
  namespace: flux-system
data:
  domain_regex: platform\.lan
  domain: platform.lan
  github_app_client_id: Iv23liZ8GHRgpx32Em2y
  issuer_group: cert-manager.io
  issuer_kind: ClusterIssuer
  issuer_name: selfsigned
  traefik_replicas: "1"

